name: Test

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  test-ubuntu:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        compiler: [gcc, clang]
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y libcurl4-gnutls-dev
      - name: Set up ${{ matrix.compiler }}
        run: |
          if [ "${{ matrix.compiler }}" == "clang" ]; then
            sudo apt-get install -y clang;
          fi
      - name: Install clib
        run: |
          git clone https://github.com/clibs/clib.git
          cd clib
          make
          sudo make install
      - name: Install dependencies
        run: make install
      - name: Run tests
        run: make CC=${{ matrix.compiler }} CFLAGS="-std=gnu11 -DNUM_THREADS=4" LDFLAGS="-pthread -latomic" test

  test-macos:
    runs-on: macos-latest
    strategy:
      matrix:
        compiler: [gcc, clang]
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: brew install curl
      - name: Install ${{ matrix.compiler }}
        run: |
          if [ "${{ matrix.compiler }}" == "gcc" ]; then
            brew install gcc;
          fi
      - name: Install clib
        run: |
          git clone https://github.com/clibs/clib.git
          cd clib
          make CC=${{ matrix.compiler }}
          sudo make install
      - name: Install dependencies
        run: make install
      - name: Run tests with ${{ matrix.compiler }}
        run: make CC=${{ matrix.compiler }} CFLAGS="-std=c11 -DNUM_THREADS=4" test

  test-windows-msvc:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ilammy/msvc-dev-cmd@v1
      - name: Install dependencies
        run: |
          choco install make
          choco install curl
      - name: Install deps
        run: |
          mkdir -p deps\aligned
          curl -L https://raw.githubusercontent.com/goodcleanfun/aligned/refs/heads/main/src/aligned.h -o deps\aligned\aligned.h
          mkdir -p deps\cpu_relax
          curl -L https://raw.githubusercontent.com/goodcleanfun/cpu_relax/refs/heads/main/src/cpu_relax.h -o deps\cpu_relax\cpu_relax.h
          mkdir -p deps\greatest
          curl -L https://github.com/silentbicycle/greatest/raw/release/greatest.h -o deps\greatest\greatest.h
          mkdir -p deps\threading
          curl -L https://raw.githubusercontent.com/goodcleanfun/threading/refs/heads/main/src/threading.h -o deps\threading\threading.h
      - name: Run tests with MSVC
        run: make CC=cl CFLAGS="/std:c11 /volatile:iso /experimental:c11atomics" test

  test-windows-mingw:
    runs-on: windows-latest
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v4
      - name: Verify GCC Version
        run: |
          gcc --version
      - name: Install curl
        run: |
          choco install curl -y
      - name: Download greatest.h
        run: |
          mkdir -p deps/aligned
          curl -L https://raw.githubusercontent.com/goodcleanfun/aligned/refs/heads/main/src/aligned.h -o deps/aligned/aligned.h
          mkdir -p deps/cpu_relax
          curl -L https://raw.githubusercontent.com/goodcleanfun/cpu_relax/refs/heads/main/src/cpu_relax.h -o deps/cpu_relax/cpu_relax.h
          mkdir -p deps/greatest
          curl -L https://github.com/silentbicycle/greatest/raw/release/greatest.h -o deps/greatest/greatest.h
          mkdir -p deps/threading
          curl -L https://raw.githubusercontent.com/goodcleanfun/threading/refs/heads/main/src/threading.h -o deps/threading/threading.h
      - name: Build and Test with MinGW
        run: |
          make CC=gcc CFLAGS="-std=c11" test